name: Lint

on:
  push:
    branches:
      - master
      - production
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - run: |
          cd src
          npm ci
  lint:
    name: Lint
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd src
          npm run lint
  hi:
    name: Lint
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'hello world'